apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bparsonsdockernodegooglecloudsdk 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bparsonsdockernodegooglecloudsdk 
    spec:
      containers:
        - name: bparsonsdockernodegooglecloudsdk 
          image: testing1.azurecr.io/bparsonsdockernodegooglecloudsdk 
          ports:
          - containerPort: default